<a href="https://colab.research.google.com/github/mhdykz/mhdykz-Implementation-of-neural-network/blob/main/Implementation%20of%20neural%20network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd


In [4]:
data_path = 'titanic.csv'
data = pd.read_csv(data_path)
print("Train Data Info:")
print(data.info())
print("\nTrain Data Sample:")
print(data.head())

Train Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None

Train Data Sample:
   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5        

In [5]:
#check for missing datas
print("Missing values in each column:")
print(data.isnull().sum())

Missing values in each column:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


In [6]:
# filling missing values ​​of 'Age' column with mean
data['Age'].fillna(data['Age'].mean(), inplace=True)

# Remove rows with many missing values
data.drop(columns=['Cabin'], inplace=True)

# Filling the 'Embarked' column with the mode
data['Embarked'].fillna(data['Embarked'].mode()[0], inplace=True)

print("\nData after handling missing values:")
print(data.isnull().sum())




Data after handling missing values:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64


دلیل اصلی نرمال‌سازی:
تفاوت در مقیاس ویژگی‌ها: داده‌های مختلف ممکن است مقادیر بسیار متفاوتی داشته باشند. مثلاً ستون Age (سن) می‌تواند مقادیری بین 0 تا 80 داشته باشد، در حالی که ستون Fare (هزینه بلیت) ممکن است مقادیری بین 0 تا چند صد داشته باشد. این تفاوت در مقیاس می‌تواند باعث شود که مدل به ویژگی‌هایی با مقیاس بزرگ‌تر حساس‌تر شود و ویژگی‌های کوچک‌تر را نادیده بگیرد.

تسریع در همگرایی مدل: زمانی که ویژگی‌ها در مقیاس مشابهی قرار بگیرند، الگوریتم‌های بهینه‌سازی (مثل نزول گرادیان) سریع‌تر و با کارایی بهتری عمل می‌کنند. اگر مقیاس ویژگی‌ها متفاوت باشد، مدل ممکن است نیاز به تعداد بیشتری از گام‌های بهینه‌سازی داشته باشد تا به یک نتیجه خوب برسد.

پیش‌فرض بسیاری از الگوریتم‌ها: بسیاری از الگوریتم‌های یادگیری ماشین فرض می‌کنند که داده‌ها دارای توزیعی نرمال هستند (میانگین 0 و واریانس 1). استانداردسازی به تنظیم داده‌ها در این توزیع کمک می‌کند.

نرمال‌سازی چگونه انجام می‌شود؟
در اینجا از استانداردسازی استفاده می‌کنیم، به این معنی که هر ویژگی به‌گونه‌ای تغییر می‌کند که دارای میانگین صفر و انحراف معیار یک باشد.

In [7]:
#normalization
from sklearn.preprocessing import StandardScaler

print("\n'Age' and 'Fare':")
print(data[['Age', 'Fare']].head())

scaler = StandardScaler()
data[['Age', 'Fare']] = scaler.fit_transform(data[['Age', 'Fare']])

print("\nNormalized 'Age' and 'Fare':")
print(data[['Age', 'Fare']].head())


'Age' and 'Fare':
    Age     Fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

Normalized 'Age' and 'Fare':
        Age      Fare
0 -0.592481 -0.502445
1  0.638789  0.786845
2 -0.284663 -0.488854
3  0.407926  0.420730
4  0.407926 -0.486337


In [8]:
# Convert properties to numeric values

data['Sex'] = data['Sex'].map({'male': 0, 'female': 1})

data = pd.get_dummies(data, columns=['Embarked'], drop_first=True)

print("\nData after encoding categorical features:")
print(data.head())


Data after encoding categorical features:
   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex       Age  SibSp  \
0                            Braund, Mr. Owen Harris    0 -0.592481      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  0.638789      1   
2                             Heikkinen, Miss. Laina    1 -0.284663      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  0.407926      1   
4                           Allen, Mr. William Henry    0  0.407926      0   

   Parch            Ticket      Fare  Embarked_Q  Embarked_S  
0      0         A/5 21171 -0.502445       False        True  
1      0          PC 17599  0.786845       False       False  
2      0  STON/O2. 3101282 -0.488854       False        True  
3      0           

در این مرحله، داده‌های آموزشی را به دو بخش ویژگی‌ها (Feature Matrix) و برچسب‌ها (Labels) تقسیم می‌کنیم. این کار به این دلیل انجام می‌شود که در الگوریتم‌های یادگیری ماشین، مدل از ویژگی‌ها برای یادگیری استفاده می‌کند و سپس برچسب‌ها را به عنوان خروجی پیش‌بینی می‌کند.

جزئیات این مرحله:
ویژگی‌ها (Xtrain):

ویژگی‌ها همان فاکتورهایی هستند که مدل از آن‌ها برای پیش‌بینی استفاده می‌کند. در مسئله Titanic، این ویژگی‌ها می‌توانند مواردی مثل کلاس بلیت (Pclass)، جنسیت (Sex)، سن (Age)، تعداد اعضای خانواده همراه (SibSp و Parch) و سایر ویژگی‌ها باشند.
هر کدام از این ستون‌ها به عنوان یک ورودی برای مدل استفاده می‌شود تا براساس این ویژگی‌ها پیش‌بینی کند که آیا یک مسافر زنده مانده یا نه.
در این مرحله، ما چند ویژگی مهم را انتخاب کرده‌ایم تا به عنوان ورودی مدل استفاده شوند:
Pclass: کلاس بلیت (1، 2 یا 3)
Sex: جنسیت (0 برای مرد، 1 برای زن)
Age: سن مسافر
SibSp: تعداد اعضای خانواده همراه (خواهر و برادر، همسر)
Parch: تعداد والدین یا فرزندان همراه
Fare: هزینه بلیت
Embarked_Q و Embarked_S: مبدا سفر (بندرهایی که مسافر سوار شده است)
برچسب‌ها (Ytrain):

برچسب‌ها مقادیری هستند که مدل باید آن‌ها را پیش‌بینی کند. در اینجا، برچسب‌ها همان Survived هستند که مشخص می‌کند آیا مسافر زنده مانده است یا نه. این ستون شامل مقادیر 0 (زنده نمانده) و 1 (زنده مانده) است.
مدل با استفاده از ویژگی‌ها سعی می‌کند برچسب درست را پیش‌بینی کند.

In [9]:
# Selection of input properties

Xtrain = data[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked_Q', 'Embarked_S']]

# Output tags (Survived)

Ytrain = data['Survived']

print("\nFeature Matrix (Xtrain):")
print(Xtrain.head())
print("\nLabels (Ytrain):")
print(Ytrain.head())


Feature Matrix (Xtrain):
   Pclass  Sex       Age  SibSp  Parch      Fare  Embarked_Q  Embarked_S
0       3    0 -0.592481      1      0 -0.502445       False        True
1       1    1  0.638789      1      0  0.786845       False       False
2       3    1 -0.284663      0      0 -0.488854       False        True
3       1    1  0.407926      1      0  0.420730       False        True
4       3    0  0.407926      0      0 -0.486337       False        True

Labels (Ytrain):
0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64


در این مرحله، برای شروع آموزش شبکه عصبی، باید وزن‌ها و بایاس‌ها را مقداردهی اولیه کنیم. شبکه‌های عصبی برای یادگیری، به وزن‌ها و بایاس‌ها در لایه‌های مختلف نیاز دارند. این وزن‌ها و بایاس‌ها در ابتدا به صورت تصادفی مقداردهی می‌شوند و سپس در طول فرآیند آموزش با استفاده از پس‌انتشار خطا (Backpropagation) و نزول گرادیان (Gradient Descent) به‌روزرسانی می‌شوند.

مفاهیم کلیدی:
وزن‌ها (Weights):

وزن‌ها مشخص می‌کنند که چقدر یک ویژگی ورودی یا خروجی یک نورون بر نورون‌های بعدی تأثیر می‌گذارد. به عبارت دیگر، وزن‌ها مشخص می‌کنند که هر ورودی چه میزان اهمیت دارد.
در شبکه عصبی، هر اتصال بین دو نورون دارای یک وزن است.
بایاس‌ها (Biases):

بایاس‌ها به مدل کمک می‌کنند تا بتواند در صورت نیاز، شیب تابع فعال‌سازی را تغییر دهد و از صرفاً یک خط مستقیم جلوگیری کند. این باعث انعطاف‌پذیری بیشتر مدل در یادگیری الگوهای پیچیده می‌شود.
بایاس‌ها معمولاً به عنوان یک عدد اضافه می‌شوند تا مدل بتواند به راحتی مقادیر خروجی را تغییر دهد.
معماری شبکه:
ما در اینجا یک شبکه عصبی با یک لایه پنهان و یک لایه خروجی داریم:

لایه ورودی: شامل تعداد ویژگی‌های ورودی است که از دیتاست می‌آیند. برای مثال، ما 8 ویژگی داریم (مثل Age، Fare و غیره).
لایه پنهان: شامل نورون‌هایی است که بین ورودی و خروجی قرار دارند. در اینجا ما 4 نورون در لایه پنهان داریم.
لایه خروجی: شامل یک نورون است که نتیجه نهایی (پیش‌بینی زنده ماندن یا نه) را می‌دهد. چون این یک مسئله دسته‌بندی دو مقداری است (زنده ماندن یا نماندن)، تنها یک نورون در لایه خروجی داریم.
جزئیات کد:
تعداد نورون‌ها در لایه‌های مختلف:

input_size: تعداد ویژگی‌ها در ورودی (در اینجا 8 ویژگی است).
hidden_size: تعداد نورون‌ها در لایه پنهان (در اینجا 4 نورون در لایه پنهان انتخاب کرده‌ایم).
output_size: تعداد نورون‌ها در لایه خروجی (در اینجا 1، زیرا خروجی ما تنها می‌گوید آیا مسافر زنده مانده یا نه).
مقداردهی اولیه وزن‌ها:

وزن‌های بین لایه ورودی و پنهان (W1) به صورت تصادفی با استفاده از تابع np.random.randn مقداردهی می‌شوند. این مقادیر تصادفی کوچک به مدل کمک می‌کنند که از یک شروع کاملاً متقارن جلوگیری شود.
به همین شکل، وزن‌های بین لایه پنهان و لایه خروجی (W2) نیز به صورت تصادفی مقداردهی می‌شوند.
مقداردهی اولیه بایاس‌ها:

بایاس‌های هر لایه (b1 و b2) در ابتدا به صورت صفر مقداردهی شده‌اند. این مقادیر در طول آموزش به‌روزرسانی خواهند شد.

In [10]:
import numpy as np

# Number of neurons in different layers
input_size = Xtrain.shape[1]  # Number of input features
hidden_size = 4  # The number of neurons in the hidden layer
output_size = 1  # Number of neurons in the output layer (binary prediction: live/dead)

# Initialize weights and biases randomly
np.random.seed(42) # For reproducibility of results
W1 = np.random.randn(input_size, hidden_size) * 0.01  # Weights between input and hidden layer
b1 = np.zeros((1, hidden_size))  # Biases of hidden layer
W2 = np.random.randn(hidden_size, output_size) * 0.01  # Weights between output and hidden layer
b2 = np.zeros((1, output_size))  # Biases of output layer

print("\nInitialized weights and biases:")
print("W1:", W1)
print("b1:", b1)
print("W2:", W2)
print("b2:", b2)



Initialized weights and biases:
W1: [[ 0.00496714 -0.00138264  0.00647689  0.0152303 ]
 [-0.00234153 -0.00234137  0.01579213  0.00767435]
 [-0.00469474  0.0054256  -0.00463418 -0.0046573 ]
 [ 0.00241962 -0.0191328  -0.01724918 -0.00562288]
 [-0.01012831  0.00314247 -0.00908024 -0.01412304]
 [ 0.01465649 -0.00225776  0.00067528 -0.01424748]
 [-0.00544383  0.00110923 -0.01150994  0.00375698]
 [-0.00600639 -0.00291694 -0.00601707  0.01852278]]
b1: [[0. 0. 0. 0.]]
W2: [[-0.00013497]
 [-0.01057711]
 [ 0.00822545]
 [-0.01220844]]
b2: [[0.]]


در این مرحله، یک تابع برای عبور رو به جلو ایجاد می‌کنیم که با استفاده از ورودی‌ها، خروجی هر لایه را محاسبه می‌کند. این تابع از فرمول‌هایی که قبلاً در تحقیق قبل بیان کردیم استفاده می‌کند.

In [11]:
import numpy as np

def forward_pass(X, W1, b1, W2, b2):
    """
    Implementation of forward pass of neural network
    X: input data
    W1, b1: hidden layer weights and biases
    W2, b2: weights and biases of the output layer
    Returns: final output (y_hat) and intermediate values ​​(z1, a1)
    """
    # calculate z1 (input to the hidden layer)
    z1 = np.dot(X, W1) + b1

    # calculate a1 (hidden layer output with hyperbolic tangent function)
    a1 = np.tanh(z1)

    # calculate z2 (input to output layer)
    z2 = np.dot(a1, W2) + b2

    # calculate y_hat (final output with sigmoid function)
    y_hat = 1 / (1 + np.exp(-z2))

    return y_hat, z1, a1


در این مرحله، یک تابع برای پس‌انتشار خطا پیاده‌سازی می‌کنیم. این تابع گرادیان‌های مورد نیاز برای به‌روزرسانی وزن‌ها و بایاس‌ها را محاسبه می‌کند.
اینجا از فرمول‌هایی که قبلاً در تحقیق قبل بیان کردیم استفاده می‌شود


In [12]:
def backpropagation(X, y, y_hat, z1, a1, W2):
    """
    Implement error backpropagation to compute gradients
    X: input data
    y: real labels
    y_hat: predicted output
    z1, a1: intermediate values ​​of the hidden layer
    W2: Output layer weights
    Returns: gradients W1, b1, W2, b2
    """
    m = X.shape[0]  # Number of samples

    # The derivative of the loss function with respect to the output of the network
    dz2 = y_hat - y

    # Compute the gradients of the output layer
    dW2 = np.dot(a1.T, dz2) / m
    db2 = np.sum(dz2, axis=0, keepdims=True) / m

    # Derivative relative to the hidden layer
    dz1 = np.dot(dz2, W2.T) * (1 - np.tanh(z1) ** 2)

    # Compute the gradients of the hidden layer
    dW1 = np.dot(X.T, dz1) / m
    db1 = np.sum(dz1, axis=0, keepdims=True) / m

    return dW1, db1, dW2, db2


در این مرحله، تابعی برای به‌روزرسانی وزن‌ها و بایاس‌ها با استفاده از گرادیان‌ها و نزول گرادیان پیاده‌سازی می‌کنیم.

In [13]:
def update_parameters(W1, b1, W2, b2, dW1, db1, dW2, db2, learning_rate):
    """
    Update weights and biases using gradient descent
    learning_rate: learning rate
    """
    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1
    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2

    return W1, b1, W2, b2


تابع پیش‌بینی با استفاده از عبور رو به جلو اجرا می‌شود تا خروجی شبکه برای ورودی جدید محاسبه شود.
از تابع forward_pass برای محاسبه خروجی شبکه استفاده می‌کنیم.
سپس خروجی‌ها (مقادیر سیگموید) را با 0.5 مقایسه می‌کنیم تا پیش‌بینی‌های نهایی (0 یا 1) به دست آید.



In [ ]:
def predict(X, W1, b1, W2, b2):
    """
    Predict output for input data X
    Returns: expected output (0 or 1)
    """
    y_hat, _, _ = forward_pass(X, W1, b1, W2, b2)
    predictions = (y_hat > 0.5).astype(int)
    return predictions
